/**
 * Codebase Map — the grep-able text layer of the committed self-index
 * (issue #15). Two-layer design: this map is the agent-facing primary
 * artifact (readable without the CLI), the SQLite db the query layer.
 *
 * Determinism contract: built purely from store queries, contains no
 * timestamps, and every section is sorted with BINARY/codepoint ordering —
 * regenerating on the same tree MUST be byte-identical, because drift
 * detection is "regenerate and diff".
 */
import type { EdgeKind, Store, SymbolRow } from './store.js';

export interface MapFile {
  path: string;
  symbols: {
    kind: string;
    name: string; // container-qualified, e.g. "Store.stats"
    span: [number, number];
    signature?: string;
  }[];
}

export interface CodebaseMap {
  stats: {
    files: number;
    symbols: number;
    edges: number;
    unresolvedEdges: number;
    byKind: Record<string, number>;
    /** per-repo breakdown (#11) — names only; roots are machine-local paths */
    byRepo: Record<string, { files: number; symbols: number }>;
  };
  files: MapFile[];
  /** file-level import graph, one entry per (from, to) pair */
  imports: { from: string; to: string }[];
  /** symbol-level resolved edges, imports excluded (already file-level above) */
  edges: { from: string; fromFile: string; to: string; toFile: string; kind: EdgeKind }[];
  /** unresolved callees aggregated by name — the boundary to the outside world */
  unresolved: { name: string; kind: EdgeKind; count: number }[];
}

const display = (s: { name: string; container: string | null }): string =>
  s.container ? `${s.container}.${s.name}` : s.name;

export function buildMap(store: Store): CodebaseMap {
  const stats = store.stats();
  // Single-repo maps stay exactly as before (#11): the repo prefix on paths
  // appears only when the db actually holds more than one repository, so the
  // committed self-index MAP.md does not churn.
  const multi = Object.keys(stats.byRepo).length > 1;
  const label = (repo: string, path: string) => (multi ? `${repo}:${path}` : path);
  const files: MapFile[] = store.listFiles().map((f) => ({
    path: label(f.repo, f.path),
    symbols: store
      .symbolsInFile(f.path, f.repo)
      .filter((s: SymbolRow) => s.kind !== 'module') // the module row duplicates the file path
      .map((s: SymbolRow) => ({
        kind: s.kind,
        name: display(s),
        span: [s.spanStart, s.spanEnd] as [number, number],
        signature: s.signature ?? undefined,
      })),
  }));

  const joined = store.resolvedEdgesJoined();
  const imports: { from: string; to: string }[] = [];
  const seenImports = new Set<string>();
  const edges: CodebaseMap['edges'] = [];
  for (const e of joined) {
    if (e.kind === 'imports') {
      const key = `${label(e.from.repo, e.from.file)} ${label(e.to.repo, e.to.file)}`;
      if (!seenImports.has(key)) {
        seenImports.add(key);
        imports.push({ from: label(e.from.repo, e.from.file), to: label(e.to.repo, e.to.file) });
      }
    } else {
      edges.push({
        from: display(e.from),
        fromFile: label(e.from.repo, e.from.file),
        to: display(e.to),
        toFile: label(e.to.repo, e.to.file),
        kind: e.kind,
      });
    }
  }

  return {
    stats: {
      files: stats.files,
      symbols: stats.symbols,
      edges: stats.edges,
      unresolvedEdges: stats.unresolvedEdges,
      byKind: sortedRecord(stats.byKind),
      byRepo: stats.byRepo,
    },
    files,
    imports,
    edges,
    unresolved: store.unresolvedSummary(),
  };
}

/** re-key a record in codepoint order so JSON output is deterministic */
function sortedRecord(rec: Record<string, number>): Record<string, number> {
  const out: Record<string, number> = {};
  for (const k of Object.keys(rec).sort()) out[k] = rec[k];
  return out;
}

export function renderMapMarkdown(map: CodebaseMap): string {
  const lines: string[] = [];
  lines.push('# Codebase Map');
  lines.push('');
  lines.push(
    '> Generated by `librarian map` (deterministic — regenerate with `npm run selfindex`,',
    '> verify with `npm run selfindex:check`). Query layer: `.librarian/self.db` via',
    '> `librarian graph <symbol> --db .librarian/self.db`.'
  );
  lines.push('');

  lines.push('## Stats');
  lines.push('');
  lines.push(`- files: ${map.stats.files}`);
  lines.push(`- symbols: ${map.stats.symbols}`);
  lines.push(`- edges: ${map.stats.edges} (unresolved: ${map.stats.unresolvedEdges})`);
  const kinds = Object.entries(map.stats.byKind)
    .map(([k, n]) => `${k}=${n}`)
    .join(', ');
  lines.push(`- symbols by kind: ${kinds}`);
  const repoNames = Object.keys(map.stats.byRepo);
  if (repoNames.length > 1) {
    const repos = repoNames
      .map((r) => `${r} (files=${map.stats.byRepo[r].files}, symbols=${map.stats.byRepo[r].symbols})`)
      .join(', ');
    lines.push(`- repos: ${repos}`);
  }
  lines.push('');

  lines.push('## Files');
  lines.push('');
  for (const f of map.files) {
    lines.push(`### ${f.path}`);
    lines.push('');
    for (const s of f.symbols) {
      const sig = s.signature ? ` \`${s.signature}\`` : '';
      lines.push(`- ${s.kind} ${s.name} L${s.span[0]}-${s.span[1]}${sig}`);
    }
    if (f.symbols.length === 0) lines.push('- (no symbols)');
    lines.push('');
  }

  lines.push('## Imports (file → file)');
  lines.push('');
  for (const i of map.imports) lines.push(`- ${i.from} → ${i.to}`);
  lines.push('');

  lines.push('## Edges (symbol → symbol, resolved)');
  lines.push('');
  for (const e of map.edges) {
    lines.push(`- ${e.fromFile} ${e.from} —${e.kind}→ ${e.toFile} ${e.to}`);
  }
  lines.push('');

  lines.push('## Unresolved (aggregated)');
  lines.push('');
  for (const u of map.unresolved) lines.push(`- ${u.count}× ${u.name} (${u.kind})`);
  lines.push('');

  return lines.join('\n');
}
